# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95660152bdbec40a2a7184da15820736ed4d86780091e0d06ff0a307d5c1e70023ff535a39859823985eb070569924522af1e586169aa219a7754377d1d1ecf9

test:
  secret_key_base: eb14b7140618238c6a2b66c5cbf8fef903087fcd356a6340f6d6a84d68f308afb1ebf9f6a32a4941f8efa39753ab6de14fd525ae6affd288ef93b76fd6e44273

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
